### ISSUE TITLE
material-ui console error when opening date-picker

### ISSUE THREAD

**Issue by dynamic11** [CDH-Studio/UpSkill#1693]
**Describe the bug**
see screen shot for error when opening date picker

**To Reproduce**

1. Go to edit education
2. Open date picker
3. See console error

**Screenshots**
![image](https://user-images.githubusercontent.com/11470442/138493891-1863324f-aee2-4b02-a913-8053ce815fc9.png)

**Comment by P4ul1029** [comment]
@dynamic11 After looking into this issue, it turns out we do not directly use or import `fade`. Instead, it is used inside `MuiPickersUtilsProvider`, a component we imported from `@material-ui/pickers`. Here are code snippets from the `material-ui/pickers` git directory that highlight what line is causing the deprecation error:

![image](https://user-images.githubusercontent.com/46769064/138511923-99723bba-bfe7-48d5-b5d1-b75f2c52bdb9.png)
![image](https://user-images.githubusercontent.com/46769064/138511982-3244c2c8-ef49-4812-8b71-080866877477.png)

There is not much we can do since it is an issue on Material-UI's end. I can close this issue unless you have any additional thoughts or concerns.

**Comment by dynamic11** [comment]
since it is not caused by us then we can close it
