### ISSUE TITLE
Unable to add to education

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#878]
**Describe the bug**
Unable to add new education

**To Reproduce**
1. Go to education edit
2. try to add new education

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21133129/93273283-80b0c180-f785-11ea-9bf7-0fcea7df669a.png)

**Additional context**

**Comment by mo-5** [comment]
Closed for not being able to replicate.

**Comment by BenJeau** [comment]
ohh @dynamic11 its the issue we encountered

**Comment by BenJeau** [comment]
I think this bug is introduced by #839 (not sure), just didn't had enough time to actually test if its because of that. But basically we were able to reproduce it months with odd numbers, but not all of them.

To reproduce:
1. Make sure in the right form section (qualifications)
2. Refresh the page
3. Enter this data
![image](https://user-images.githubusercontent.com/22248828/93375573-58c56a80-f826-11ea-94bf-b00b041d96c3.png)
4. See error
