### ISSUE TITLE
Make frontend react bundle smaller

### ISSUE THREAD

**Issue by mo-5** [CDH-Studio/UpSkill#975]
What's everyone's opinion on this? It seems like a pretty large package and something we would need to maintain. We are only using it in a few places. 

The advantages of removing this are: 
- Speed up Jenkins build and local build (1 less package to install) 
- Won't need to maintain when they release new updates 
- Speed up the application for the client ( the VPN is extremely slow so making the build package as small as possible should be a priority) 

The disadvantage is we need to convert all the functions to vanilla js.

Let me know what you guys think.

**Comment by mo-5** [comment]
Also, I am not sure if we are using the following packages 
- serve ( I think this is for webpack / maybe moved to dev dependencies)
- query-string

Should these be moved to dev dependencies: 
- prop-types
- antd-dayjs-webpack-plugin
- webpack-bundle-analyzer
- webpackbar

**Comment by mo-5** [comment]
The main concern with this is the performance on the VPN. Something we need to keep in mind which is why I think this is a prod blocker. If the performance is not good we will lose interest very fast.

**Comment by BenJeau** [comment]
- `serve` is used to serve the built production application, so I don't think that one should go in the dev deps
- `query-string` is used to extract the vars from the url, ex: `?classifications[]=asfadsf&searchValue=sdfdsfd` in the results page

For the others, I think you can put them in the dev dependencies, but I think our current linter settings will complain, so we would need to modify it.

Quick question on the concern for the performance on the VPN, is this related to the speed of Jenkins is being built, or the size of the react bundle delivered to the client web browser? From this PR #930, the bundle is less than 1 MB, which imo is small enough and then gets unzipped on the client. Or is the network in inspect element saying otherwise? I don't understand why the performance on the VPN is slow, maybe its simply related to the fact that our application is outside the network?

**Comment by BenJeau** [comment]
Wonder if #991 would make it smaller, since it doesnt rely on `craco` nor `react-scripts`.

> Edit: nevermind that doesn't makes sense, since those are just tools and are not incorporated inside the react build

**Comment by BenJeau** [comment]
Kind of a regression here #1015, since I removed the ant design day.js webpack plugin (it was crashing the application, I would rather the app to be big than to crash right now)...

**Comment by mo-5** [comment]
This issue can be closed since most of the big modules have been tackled
